# Fallback times for when location-based sunrise/sunset times are unavailable.
# NOTE: Times must be in 24-hour, HH:MM:SS format.
[fallback]
sunrise = "06:30:00"
sunset = "18:30:00"

# Location settings for getting sunrise/sunset times automatically.
[location]
enabled = true

# Uncomment and set the following values if setting manually:
# longitude = 0.0
# latitude = 0.0
